<a href="https://colab.research.google.com/github/ubotirov77/ai-foundation-/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
myDataSet={
    "cars":["BMW","MERC","FORD","Tesla","Ferrari","Volvo","GM"],
    "counts":[23,54,76,120,32,12,34]
}
df=pd.DataFrame(myDataSet)
print(df)

      cars  counts
0      BMW      23
1     MERC      54
2     FORD      76
3    Tesla     120
4  Ferrari      32
5    Volvo      12
6       GM      34

In [3]:
df.head() #default 5 rows

      cars  counts
0      BMW      23
1     MERC      54
2     FORD      76
3    Tesla     120
4  Ferrari      32

In [4]:
df.tail(3) #default 5 rows (desc)

      cars  counts
4  Ferrari      32
5    Volvo      12
6       GM      34

In [5]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [6]:
df.dtypes

cars      object
counts     int64
dtype: object

In [7]:
print(df)

      cars  counts
0      BMW      23
1     MERC      54
2     FORD      76
3    Tesla     120
4  Ferrari      32
5    Volvo      12
6       GM      34

In [9]:
df.describe()

           counts
count    7.000000
mean    50.142857
std     37.293559
min     12.000000
25%     27.500000
50%     34.000000
75%     65.000000
max    120.000000

In [10]:
df.iloc[3:]

      cars  counts
3    Tesla     120
4  Ferrari      32
5    Volvo      12
6       GM      34

In [11]:
df.loc[2:4,"cars"]

2       FORD
3      Tesla
4    Ferrari
Name: cars, dtype: object

In [12]:
print(df)

      cars  counts
0      BMW      23
1     MERC      54
2     FORD      76
3    Tesla     120
4  Ferrari      32
5    Volvo      12
6       GM      34

In [13]:
df["counts"]>60

0    False
1    False
2     True
3     True
4    False
5    False
6    False
Name: counts, dtype: bool

In [14]:
df[df["counts"]>60]

    cars  counts
2   FORD      76
3  Tesla     120

In [15]:
df[df["cars"]=="Tesla"]

    cars  counts
3  Tesla     120

In [16]:
df["cars"]=="Tesla"

0    False
1    False
2    False
3     True
4    False
5    False
6    False
Name: cars, dtype: bool

In [17]:
df.mean(numeric_only=True)

counts    50.142857
dtype: float64

In [18]:
df['counts'].mean()

np.float64(50.142857142857146)

In [19]:
df.sum()

cars      BMWMERCFORDTeslaFerrariVolvoGM
counts                               351
dtype: object

In [20]:
df.min()

cars      BMW
counts     12
dtype: object

In [22]:
df.max()

cars      Volvo
counts      120
dtype: object

In [23]:
df.median(numeric_only=True)

counts    34.0
dtype: float64

In [24]:
df.count()

cars      7
counts    7
dtype: int64

In [25]:
df.std(numeric_only=True)

counts    37.293559
dtype: float64