<a href="https://colab.research.google.com/github/ubotirov77/ai-foundation-/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
myDataSet={
    "cars":["BMW","MERC","FORD","Tesla","Ferrari","Volvo","GM"],
    "counts":[23,54,76,120,32,12,34]
}
df=pd.DataFrame(myDataSet)
print(df)

      cars  counts
0      BMW      23
1     MERC      54
2     FORD      76
3    Tesla     120
4  Ferrari      32
5    Volvo      12
6       GM      34

In [3]:
df.head() #default 5 rows

      cars  counts
0      BMW      23
1     MERC      54
2     FORD      76
3    Tesla     120
4  Ferrari      32

In [4]:
df.tail(3) #default 5 rows (desc)

      cars  counts
4  Ferrari      32
5    Volvo      12
6       GM      34

In [5]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [6]:
df.dtypes

cars      object
counts     int64
dtype: object

In [7]:
print(df)

      cars  counts
0      BMW      23
1     MERC      54
2     FORD      76
3    Tesla     120
4  Ferrari      32
5    Volvo      12
6       GM      34

In [9]:
df.describe()

           counts
count    7.000000
mean    50.142857
std     37.293559
min     12.000000
25%     27.500000
50%     34.000000
75%     65.000000
max    120.000000

In [10]:
df.iloc[3:]

      cars  counts
3    Tesla     120
4  Ferrari      32
5    Volvo      12
6       GM      34

In [11]:
df.loc[2:4,"cars"]

2       FORD
3      Tesla
4    Ferrari
Name: cars, dtype: object

In [12]:
print(df)

      cars  counts
0      BMW      23
1     MERC      54
2     FORD      76
3    Tesla     120
4  Ferrari      32
5    Volvo      12
6       GM      34

In [13]:
df["counts"]>60

0    False
1    False
2     True
3     True
4    False
5    False
6    False
Name: counts, dtype: bool

In [14]:
df[df["counts"]>60]

    cars  counts
2   FORD      76
3  Tesla     120

In [15]:
df[df["cars"]=="Tesla"]

    cars  counts
3  Tesla     120

In [16]:
df["cars"]=="Tesla"

0    False
1    False
2    False
3     True
4    False
5    False
6    False
Name: cars, dtype: bool

In [17]:
df.mean(numeric_only=True)

counts    50.142857
dtype: float64

In [18]:
df['counts'].mean()

np.float64(50.142857142857146)

In [19]:
df.sum()

cars      BMWMERCFORDTeslaFerrariVolvoGM
counts                               351
dtype: object

In [20]:
df.min()

cars      BMW
counts     12
dtype: object

In [22]:
df.max()

cars      Volvo
counts      120
dtype: object

In [23]:
df.median(numeric_only=True)

counts    34.0
dtype: float64

In [24]:
df.count()

cars      7
counts    7
dtype: int64

In [26]:
df.std(numeric_only=True)

counts    37.293559
dtype: float64

In [27]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "Ford" ],
    "counts": [3, 7, None, 8, 1, 9, None]
}

df_missing = pd.DataFrame(data_with_missing)

print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [28]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [29]:
df_missing.dropna(subset=['cars'])

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
6     Ford     NaN

In [32]:
df_missing.fillna({"cars": "unknown", "counts": 0})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     8.0
4  Ferrari     1.0
5  unknown     9.0
6     Ford     0.0

In [58]:
df = pd.read_csv("Titanic-Dataset.csv")
# df.head(30)

#df = pd.read_excel("test.xlsx")
df.tail(5)

 #df = pd.read_json("Titanic-Dataset.json")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [54]:
df.to_excel("test.xlsx")